services:
  haproxy:
    image: haproxy:3.1-alpine
    volumes:
      - ../lb/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - sock:/run/sock
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "16M"
    depends_on:
      - api1
      - api2

  api1: &api
    image: rinha/api-swift:latest
    environment:
      INDEX_PATH: /data/ivf.bin
      EXACT_PATH: /data/exact.bin
      RESOURCES_PATH: /resources
      SOCKET_PATH: /run/sock/api1.sock
      NPROBE_FULL: "5"
    volumes:
      - sock:/run/sock
    cpuset: "1,2"
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "162M"

  api2:
    <<: *api
    environment:
      INDEX_PATH: /data/ivf.bin
      EXACT_PATH: /data/exact.bin
      RESOURCES_PATH: /resources
      SOCKET_PATH: /run/sock/api2.sock
      NPROBE_FULL: "5"
    cpuset: "2,3"

volumes:
  sock:
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=1M"
